# Generated by Django 4.2.6 on 2023-12-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APImovie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
