# Generated by Django 4.2.6 on 2023-11-19 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APImovie', '0002_collection_genre_language_productioncompany_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('is_public', models.BooleanField(default=True, null=True)),
                ('upvotes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('downvotes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='lists', to='APImovie.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
