# Generated by Django 4.2.6 on 2023-11-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APImovie', '0004_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
