# Generated by Django 4.2.6 on 2023-11-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APImovie', '0006_alter_movielist_options_alter_movielist_id_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movielist',
            name='total_time_of_movies',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
